title: Firxiao's Blog
description: 记录些有用的东西
author: Firxiao
github: https://github.com/firxiao
about: 记录些有用的东西
disqus_shortname: firxiao
google_analytics: UA-144707637-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-github
      link: "https://github.com/firxiao"

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://blog.firxiao.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
